-- Transactional validator boundary checks; no persistent data is written.
begin;
do $$ begin
  if lotline_private.valid_plan_allocations('[{"mint":"XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp","bps":"1000"},{"mint":"XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX","bps":"1000"},{"mint":"Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh","bps":"1000"},{"mint":"XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB","bps":"1000"},{"mint":"XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W","bps":"1000"},{"mint":"Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ","bps":"1000"},{"mint":"XsGHwSbPaUJu6r5dtJLHXkXenPgCQf4Sx2hb4e2sbCZ","bps":"1000"},{"mint":"Xs2XDRGh6AhivmYgaVa8woDGKGccR1WnnGnw9vqSWD9","bps":"1000"},{"mint":"XswbinNKyPmzTa5CskMbCPvMW6G5CMnZXZEeQSSQoie","bps":"1000"},{"mint":"XscSc1zjbVizEnhCzzehJ9fzztm3WRKdn9pjmriKDuN","bps":"1000"}]'::jsonb) is distinct from true then raise exception 'Ten registered assets validation failed'; end if;
  if lotline_private.valid_plan_allocations('[{"mint":"XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp","bps":"10000"},{"mint":"XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX","bps":"0"},{"mint":"Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh","bps":"0"},{"mint":"XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB","bps":"0"},{"mint":"XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W","bps":"0"},{"mint":"Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ","bps":"0"},{"mint":"XsGHwSbPaUJu6r5dtJLHXkXenPgCQf4Sx2hb4e2sbCZ","bps":"0"},{"mint":"Xs2XDRGh6AhivmYgaVa8woDGKGccR1WnnGnw9vqSWD9","bps":"0"},{"mint":"XswbinNKyPmzTa5CskMbCPvMW6G5CMnZXZEeQSSQoie","bps":"0"},{"mint":"XscSc1zjbVizEnhCzzehJ9fzztm3WRKdn9pjmriKDuN","bps":"0"},{"mint":"XsHtf5RpxsQ7jeJ9ivNewouZKJHbPxhPoEy6yYvULr7","bps":"0"}]'::jsonb) is distinct from false then raise exception 'Eleven assets validation failed'; end if;
  if lotline_private.valid_plan_allocations('[{"mint":"XsGHwSbPaUJu6r5dtJLHXkXenPgCQf4Sx2hb4e2sbCZ","bps":"10000"}]'::jsonb) is distinct from true then raise exception 'New stock outside original six validation failed'; end if;
  if lotline_private.valid_plan_allocations('[{"mint":"XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp","bps":"5000"},{"mint":"XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp","bps":"5000"}]'::jsonb) is distinct from false then raise exception 'Duplicate mints validation failed'; end if;
  if lotline_private.valid_plan_allocations('[{"mint":"11111111111111111111111111111111","bps":"10000"}]'::jsonb) is distinct from false then raise exception 'Unknown mint validation failed'; end if;
end $$;
rollback;
select 'PASS: expanded catalog, ten-asset boundary, duplicate and unknown mint rejection; transaction rolled back' as result;
