import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Check, Fingerprint, Layers3, ShieldCheck } from 'lucide-react';
import { SiteHeader, SiteFooter } from '@/components/site-shell';

export const metadata: Metadata = { title: 'How it works' };

export default function HowItWorks() {
  return <><SiteHeader active="how" /><main id="main" className="how-page page-width">
    <div className="how-intro"><p className="eyebrow">A LITTLE CONTEXT GOES A LONG WAY</p><h1>Know what goes in.<br /><span>See what could come out.</span></h1><p>Lotline helps you plan a new USDC contribution across up to three xStocks. You choose the assets and percentages. We handle the arithmetic and request estimates.</p></div>
    <div className="how-layout"><div className="how-main">
      <section className="how-step"><span className="step-number">01</span><div><h2>Make the plan yours.</h2><p>Choose from a small catalog verified against the xStocks issuer and Solana. Enter percentages totaling 100% and a USDC budget. The split applies only to this new contribution.</p><p>Budgets accept up to six decimal places, up to 1,000,000 USDC. Percentages accept two. Any remaining micro-USDC goes to the largest fractional remainder, with ties settled in your basket order. Every micro-USDC is accounted for.</p></div></section>
      <section className="how-step"><span className="step-number">02</span><div><h2>Add context, if you want.</h2><p>Paste a public Solana wallet address to read current xStock and mainnet USDC balances. No wallet extension or signature is needed. Lotline combines all token accounts for each selected asset.</p><p>xStocks can use Scaled UI Amount, so displayed units may change after corporate actions. We use mint-aware conversion with the current onchain multiplier and chain time. If conversion cannot be verified, units are unavailable.</p></div></section>
      <section className="how-step"><span className="step-number">03</span><div><h2>Request a moment-in-time estimate.</h2><p>Select “Get estimates” to request Jupiter quotes for your allocated USDC amounts. Quotes contain no wallet address or transaction. Estimated resulting holdings are calculated by adding raw token amounts first, then converting the total to displayed units.</p><p>Quotes become stale after 30 seconds or the provider’s expiry, whichever is sooner. Refresh explicitly for new estimates. A missing route, issuer halt, or unavailable service is shown for the affected asset. Review current amounts and fees on Jupiter.</p></div></section>
      <section className="how-step"><span className="step-number">04</span><div><h2>Take your plan with you.</h2><p>Copy your plan or download a CSV with exact allocations, verified mints, estimates, and retrieval times. Copy an asset’s mint, open Jupiter, select the asset, and enter the copied USDC amount. Review the trade yourself.</p><p>Lotline cannot observe a purchase. Loading balances again is simply a new read of the wallet’s current onchain state.</p><Link href="/app" className="button primary">Make a plan <ArrowRight size={16} /></Link></div></section>
    </div><aside className="how-aside"><div className="principles-card"><ShieldCheck size={24} /><h3>Intentionally simple.</h3><ul><li><Check size={15} /> Your own contribution percentages</li><li><Check size={15} /> Public, read-only balances</li><li><Check size={15} /> Optional account. No custody</li><li><Check size={15} /> No signed or submitted transactions</li></ul></div><div className="aside-note"><Fingerprint size={21} /><h3>Keep your plan close.</h3><p>Your basket and budget are saved in your browser’s local storage. An optional account lets you explicitly save named plans across devices. Wallet addresses are never included.</p></div><div className="aside-note"><Layers3 size={21} /><h3>Try a clear example.</h3><p>Example mode uses labeled, deterministic synthetic balances and quotes, including a non-unit multiplier. It works without any credentials.</p><Link href="/app?mode=example" className="text-button">Try the example <ArrowUpRight size={15} /></Link></div></aside></div>
  </main><SiteFooter /></>;
}
